export enum SchoolAdminRole {
  OWNER = "OWNER",
  PRINCIPAL = "PRINCIPAL",
  DIRECTOR = "DIRECTOR",
  CHAIRMAN = "CHAIRMAN",
  DEAN = "DEAN",
  ADMINISTRATOR = "ADMINISTRATOR",
  VICE_PRINCIPAL = "VICE_PRINCIPAL",
  HEADMASTER = "HEADMASTER",
  TRUSTEE = "TRUSTEE",
  CO_FOUNDER = "CO_FOUNDER",
}
